### ISSUE TITLE
Loading Problems

### ISSUE THREAD

**Issue by CarpeDiemRo** [custom-cards/surveillance-card#17]
```
cards: null
type: 'custom:surveillance-card'
thumb_interval: 10
update_interval: 1
cameras:
  - entity: camera.hol_si_intrare
  - entity: camera.bucatarie
```

OS: macOS
Browsers: Safari, Chrome
HA: 0.99

When I switch to CCTV tab in HA, the main image is not loaded. 
Work arround: refresh browser

The second camera is not turned on, therefore is not displayed

![Screenshot 2019-09-19 at 09 33 50](https://user-images.githubusercontent.com/38489167/65219150-ac409380-dac0-11e9-976f-0720ac08a58e.png)
