### ISSUE TITLE
Refresh interval issue

### ISSUE THREAD

**Issue by CarpeDiemRo** [custom-cards/surveillance-card#18]
```
cards: null
type: 'custom:surveillance-card'
thumb_interval: 10
update_interval: 1
cameras:
  - entity: camera.hol_si_intrare
  - entity: camera.bucatarie
```

OS: macOS
Browsers: Safari, Chrome

Even though update interval is set to 1 (one second) the new frame is loaded with delay from 4 to 5 seconds.
