### ISSUE TITLE
No card type found

### ISSUE THREAD

**Issue by imwireless** [custom-cards/surveillance-card#41]
I installed via HACS but am unable to get this working.  

![image](https://user-images.githubusercontent.com/52220457/109197939-9e8a4580-776b-11eb-9edd-58993ed95e0e.png)

![image](https://user-images.githubusercontent.com/52220457/109197988-ac3fcb00-776b-11eb-846a-397ed76c2dea.png)

Any suggestions?

**Comment by niemyjski** [comment]
Did you install this via hacs?

**Comment by stu1811** [comment]
> Did you install this via hacs?

I have the same issue. I installed via hacs. Let me know if I can provide any debug or logging info.

![image](https://user-images.githubusercontent.com/12236842/115172048-6845b400-a092-11eb-9603-1c3518481829.png)

![image](https://user-images.githubusercontent.com/12236842/115172162-aa6ef580-a092-11eb-8fe8-ef418bad33f6.png)

**Comment by niemyjski** [comment]
The type is not valid yaml, you need to escape it: `type: 'custom:surveillance-card'`

**Comment by stu1811** [comment]
Do you mean I need the single quotes?

**Comment by davidjmorin** [comment]
> Do you mean I need the single quotes?

Yes.  Just use the single quotes and you should be good.

**Comment by niemyjski** [comment]
It just needs to be quoted :)

**Comment by stu1811** [comment]
> The type is not valid yaml, you need to escape it: `type: 'custom:surveillance-card'`

I'm still seeing the error

![Screenshot_20210419-143757_Chrome.jpg](https://user-images.githubusercontent.com/12236842/115286297-e9e22400-a11c-11eb-91e1-7cfd54d4366c.jpg)

**Comment by stu1811** [comment]
I finally got this to work using the below code. The only issue I'm having now is when I click the video record it takes a still image.
```
type: 'custom:surveillance-card'
thumb_interval: 15
update_interval: 2
recording_duration: 10
show_capture_buttons: true
cameras:
  - entity: camera.cam1
  - entity: camera.cam2
  - entity: camera.cam3
  - entity: camera.cam4
```
