### ISSUE TITLE
Add light entity

### ISSUE THREAD

**Issue by OToussaint** [custom-cards/surveillance-card#60]
I have a camera with a light that is defined at the same time as the camera in HA.
Therefore, I'd like to control it in the surveillance card too.
It could also be a light in the same area as the camera, the feature will be as useful in my opinion, exactly as the motion sensor, independent of the camera in the config.

Like so:

```
cameras:
  - entity: camera.front_porch
    motion_entity: binary_sensor.front_porch_motion
    light_entity: light.front_porch
```
