### ISSUE TITLE
I have two cameras, but only one is shown (how to solve overlap)?

### ISSUE THREAD

**Issue by Klagio** [custom-cards/surveillance-card#62]
I think its below the first, how to be able to see both cameras?

I tried putting two cards but they overlap partially
```

      - type: custom:surveillance-card
        thumb_interval: 15
        update_interval: 2
        focus_motion: true
        recording_duration: 10
        show_capture_buttons: true
        camera_view: ''
        cameras:
          - entity: camera.1
            motion_entity: binary_sensor.nuc_i5_office_terrace1_motion
```
```

      - type: custom:surveillance-card
        thumb_interval: 15
        update_interval: 2
        focus_motion: true
        recording_duration: 10
        show_capture_buttons: true
        camera_view: ''
        cameras:
          - entity: camera.2
            motion_entity: binary_sensor.nuc_i5_office_terrace1_motion
```
