### ISSUE TITLE
Unable to style

### ISSUE THREAD

**Issue by SoulRaven** [custom-cards/surveillance-card#63]
i having troubles with styling the custom:surveillance-card, any attempt on using:
```yaml

style: |
```
are failing, and no style is applied.
any suggestions?

also is not working if i put the card inside the costum:mod-card, nothing is render and load

```yaml
title: Outdoor Cams
icon: mdi:cctv
panel: true
cards:
  - type: custom:mod-card
    card:
      type: custom:surveillance-card
      thumb_interval: 1
      thumb_position: top
      update_interval: 1
      recording_duration: 10
      show_capture_buttons: false
      camera_view: "live"
      focus_motion: true
      cameras:
        - entity: camera.sec_01_profilename001
          #motion_entity: camera.pgmo_sec_pro_01_profilename025
        - entity: camera.sec_01_profilename002
          #motion_entity: camera.pgmo_sec_pro_01_profilename026
        - entity: camera.sec_01_profilename003
          #motion_entity: camera.pgmo_sec_pro_01_profilename027
        - entity: camera.sec_01_profilename004
          #motion_entity: camera.pgmo_sec_pro_01_profilename028
        - entity: camera.sec_01_profilename005
          #motion_entity: camera.pgmo_sec_pro_01_profilename029
        - entity: camera.sec_01_profilename006
          #motion_entity: camera.pgmo_sec_pro_01_profilename030
        - entity: camera.sec_01_profilename007
          #motion_entity: camera.pgmo_sec_pro_01_profilename031
        - entity: camera.sec_01_profilename008
          #motion_entity: camera.pgmo_sec_pro_01_profilename032
    card-mod:
      style: |
        .container.thumbs-top .thumbs {
            color: red !important;
        }
```
