### ISSUE TITLE
Navigate through cameras

### ISSUE THREAD

**Issue by lobhater** [custom-cards/surveillance-card#64]
I have tried to search and search and could not find a solution so I hope I am not just missing something. When setting thumb_position: none is there still a way to switch between the cameras?  Such as the left and right arrows of a standard frigate card?  Thanks for all your work on this, I use it daily  

```
type: custom:surveillance-card
thumb_interval: 15
update_interval: 2
recording_duration: 10
show_capture_buttons: false
focus_motion: true
thumb_position: none
camera_view: ''
cameras:
  - entity: camera.driveway
    motion_entity: binary_sensor.driveway_motion
  - entity: camera.front_door
    motion_entity: binary_sensor.front_door_motion
  - entity: camera.furnace_room
    motion_entity: binary_sensor.furnace_room_motion
```
